version: "3.8"

services:
  sentiment_analysis:
    image: sentiment_analysis:1.0
    ports:
      - "80:8000"

    environment:
      API_KEY: 1234
    depends_on:
      - db


  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    


