name: Building Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_push_to_dockerhub:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker Login
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: mohannadkarim/dummy_project:1.0

  deploy_to_EC2:
    
    runs-on: ubuntu-latest
    needs: build_and_push_to_dockerhub
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_PEM_KEY }}
  
    - name: Add EC2 host to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
  
    - name: Deploy application via SSH
      run: |
        EC2_USER="ubuntu"  
        EC2_TARGET="${{ secrets.EC2_HOST }}"
        DOCKER_IMAGE_NAME="mohannadkarim/dummy_project:1.0"
  
        echo "Attempting to deploy to ${EC2_USER}@${EC2_TARGET}"
  
        ssh "${EC2_USER}@${EC2_TARGET}" << 'EOF'
          echo "Successfully connected to EC2 instance."
          echo "Stopping existing container (if any)..."
          sudo docker stop dummy_project || true
          sudo docker rm dummy_project || true
          sudo docker rmi dummy_project:1.0
          cd dummy-sentiment-analysis
  
          echo "Pulling latest Docker image: ${DOCKER_IMAGE_NAME}..."
          sudo docker pull ${DOCKER_IMAGE_NAME}
  
          echo "Running new container..."
          sudo docker compose up
          
          echo "Deployment to EC2 complete."
        EOF
  

    
