name: Deploy to EC2 via SSH

on:
  push:
    branches:
      - main

jobs:
  build_and_push_to_dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.USERNAME }}/dummy_project:1.0

  deploy_to_ec2:
    runs-on: ubuntu-latest
    needs: build_and_push_to_dockerhub
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_PEM_KEY }}

      - name: Add EC2 host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy application via SSH
        run: |
          ssh -T ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            
            echo "Successfully connected to EC2 instance."

            echo "Stopping existing container (if any)..."

            
            cd dummy-sentiment-analysis
            sudo docker compose down || true

            # Change to the project directory where the docker-compose.yaml is located.
            
            # Pull the latest image and restart the container using docker compose.
            echo "Pulling latest Docker image and restarting container..."
            sudo docker compose up -d

            echo "Deployment to EC2 complete."
          EOF
